apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"keycloak.org/v1alpha1","kind":"Keycloak","metadata":{"labels":{"app":"sso"},"name":"keycloak","namespace":"rhsso"},"spec":{"externalAccess":{"enabled":true},"instances":1}}'
  generation: 1
  labels:
    app: sso
  name: keycloak
  namespace: rhsso
spec:
  externalAccess:
    enabled: true
