apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"name":"books-frontend-v2","namespace":"secure-oauth"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"books-frontend","version":"v2"}},"template":{"metadata":{"labels":{"app":"books-frontend","version":"v2"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"book-config"}}],"image":"quay.io/redhattraining/3scale-books-frontend:v2","name":"books-frontend","ports":[{"containerPort":3000}]}]}}}}'
  creationTimestamp: "2022-04-19T02:32:57Z"
  generation: 1
  name: books-frontend-v2
  namespace: secure-oauth
  resourceVersion: "280874"
  uid: b5e7c17d-7cce-4db5-b341-2469b5917339
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: books-frontend
      version: v2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: books-frontend
        version: v2
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: book-config
        image: quay.io/redhattraining/3scale-books-frontend:v2
        imagePullPolicy: IfNotPresent
        name: books-frontend
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-04-19T02:32:57Z"
    lastUpdateTime: "2022-04-19T02:33:33Z"
    message: ReplicaSet "books-frontend-v2-6dd5c697d6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-04-19T10:43:41Z"
    lastUpdateTime: "2022-04-19T10:43:41Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
