apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"keycloak.org/v1alpha1","kind":"KeycloakRealm","metadata":{"labels":{"realm":"do240"},"name":"do240-keycloakrealm","namespace":"rhsso"},"spec":{"instanceSelector":{"matchLabels":{"app":"sso"}},"realm":{"displayName":"do240","enabled":true,"id":"do240","realm":"do240"}}}'
  creationTimestamp: "2022-04-19T02:32:55Z"
  finalizers:
  - realm.cleanup
  generation: 1
  labels:
    realm: do240
  name: do240-keycloakrealm
  namespace: rhsso
  resourceVersion: "281582"
  uid: c791781c-0003-44df-9248-3776310c4f2f
spec:
  instanceSelector:
    matchLabels:
      app: sso
  realm:
    displayName: do240
    enabled: true
    id: do240
    realm: do240
status:
  loginURL: ""
  message: ""
  phase: reconciling
  ready: true
